Code Review: Calculator App - Milestone four
Milypm/calculator-app pull request #3
Opened 2021-07-09 17:53 UTC by Milypm

For this project, I implement the logic for doing the calculations on the app:

- Create the 'logic' directory inside 'src'
- Create calculate and operate components (inside 'logic' directory)
- Write several conditions depending on the requested operation/number
- Import and use Big.js library to perform the operations

Tools:
- JavaScript
- Big.js
- React
- React.Dom
- JSX
- Eslint

2021-07-10 08:44 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED 🟡  ♻️ 

HI @Milypm, you have done a great job in meeting almost all the requirements for this milestone. However, there is one minor change that needs to be addressed before this can be approved. Check my comments below ⬇️ 

*All the best and good luck* 💪 

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-07-10 08:44 UTC, Elbie-em commented on src/logic/calculate.js
> +  let { total, next, operation } = calcObj;
- [ ] calcObj and btnName should be parameters as they will be passed to calculate as arguments. This illustration implies that you are passing an object and destructuring the two from that object. Kindly fix this.

2021-07-10 08:44 UTC, Elbie-em commented on src/logic/operate.js
> +const operate = ({ numberOne, numberTwo, operation }) => {
- [ ] numberOne, numberTwo, and operation should be parameters as each will be passed to operate as arguments. This illustration implies that you are passing an object and destructuring the three from that object. Your implementation of operate in calculate.js clearly shows you are not passing an object but arguments. Kindly fix this.

2021-07-12 00:50 UTC, NtwaliHeritier approved these changes
### **STATUS: APPROVED👍️👍️**

Hello @Milypm 
Great work making the requested changes.👏️👏️
You can merge👍️👍️

Happy coding💻️💻️

2021-07-12 14:08 UTC, merged